# Generated by Django 3.2 on 2021-04-14 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=100)),
                ("month_actual", models.CharField(max_length=100)),
                ("month_target", models.CharField(max_length=100)),
                ("ytd_actual", models.CharField(max_length=100)),
                ("ytd_target", models.CharField(max_length=100)),
                (
                    "file_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.file",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
