# Generated by Django 3.2 on 2021-04-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0002_filedata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filedata",
            name="file_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="administrator.file"
            ),
        ),
    ]
